//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_API_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_MASTER
    {
        public int ACC_ID { get; set; }
        public Nullable<int> ACCOUNT_NO { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public Nullable<int> ACC_TYPE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    }
}
