//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_API_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.ChartOfAccounts = new HashSet<ChartOfAccount>();
        }
    
        public int ACC_ID { get; set; }
        public int ACCOUNT_NO { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string ACC_TYPE { get; set; }
        public decimal BALANCE { get; set; }
        public int STATUS { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public int CREATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount> ChartOfAccounts { get; set; }
    }
}
