//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_API_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHART_ACC
    {
        public int COA_ID { get; set; }
        public int ACC_ID { get; set; }
        public string ACCOUNT_DESCRIPTION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
    }
}
