//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_API_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount
    {
        public int COA_ID { get; set; }
        public int ACC_ID { get; set; }
        public string ACCOUNT_DESCRIPTION { get; set; }
        public int STATUS { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_AT { get; set; }
        public int UPDATED_BY { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
