//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_API_PROJECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Financial_Management_SystemEntities : DbContext
    {
        public Financial_Management_SystemEntities()
            : base("name=Financial_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC_MASTER> ACC_MASTER { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CHART_ACC> CHART_ACC { get; set; }
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<USER_INFO> USER_INFO { get; set; }
    }
}
